version: '3.8'

services:
  # Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: evoting_app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: evotingc_evoting
      DB_USERNAME: evotingc_evoting
      DB_PASSWORD: MPInpkQMQgXn

  # Web Server (Nginx)
  webserver:
    image: nginx:alpine
    container_name: evoting_webserver
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4000:80"
    networks:
      - laravel
    depends_on:
      - app

  # MySQL Database
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: evoting_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: MPInpkQMQgXn
      MYSQL_DATABASE: evotingc_evoting
      MYSQL_USER: evotingc_evoting
      MYSQL_PASSWORD: MPInpkQMQgXn
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  laravel:
    driver: bridge
